"""Subclass of AddFactorDialog, which is generated by wxFormBuilder."""

import wx
import GeneratedGUI

# Implementing AddFactorDialog
class PexDbViewerAddFactorDialog( GeneratedGUI.AddFactorDialog ):
	def __init__( self, parent, alreadyconnected : list):
		GeneratedGUI.AddFactorDialog.__init__( self, parent )
		self._alrconn = alreadyconnected

