"""Subclass of EditProjectDialog, which is generated by wxFormBuilder."""

import wx
from wx.core import NOT_FOUND
import GeneratedGUI
from PersistClasses import *
import sqlitepersist as sqp

# Implementing EditProjectDialog
class PexDbViewerEditProjectDialog( GeneratedGUI.EditProjectDialog ):

	@property
	def project(self):
		return self._project

	def __init__( self, parent, fact : sqp.SQFactory, proj : Project ):
		GeneratedGUI.EditProjectDialog.__init__( self, parent )

		self._fact = fact
		self._project = proj

	def EditProjectDialogOnShow( self, event ):
		if event.Show is False:
			return

		self.fill_gui(self._project)

	def fill_gui(self, pro):
		self.m_nameTB.SetValue(pro.name)
		self.m_isArchivedCBX.SetValue(pro.isarchived)
		ps_q = sqp.SQQuery(self._fact, ProjectStatusCat).where(ProjectStatusCat.LangCode==self._fact.lang)
		self._pstatcat = []
		ct = 0
		sel = wx.NOT_FOUND
		for ps in ps_q:
			self._pstatcat.append(ps)
			if not pro.status is None and ps.code == pro.status.code:
				sel = ct
			ct += 1
		choicevals = list(map(lambda ps : ps.value, self._pstatcat))
		self.m_projectstatusCOB.SetItems(choicevals)
		self.m_projectstatusCOB.SetSelection(sel)

	def m_okcancelBUTSOnOKButtonClick( self, event ):
		self._project.name = self.m_nameTB.GetValue()
		self._project.isarchived = self.m_isArchivedCBX.GetValue()

		statidx = self.m_projectstatusCOB.GetSelection()
		if statidx == wx.NOT_FOUND:
			self._project.status = None
		else:
			self._project.status = self._pstatcat[statidx]

		self.EndModal(wx.ID_OK)
		

