"""Subclass of OpenProjectDialog, which is generated by wxFormBuilder."""

import wx
import GeneratedGUI
import sqlitepersist
import sqlitepersist as sqp
from PersistClasses import *

# Implementing OpenProjectDialog
class PexDbViewerOpenProjectDialog( GeneratedGUI.OpenProjectDialog ):
	def __init__(self, parent, fact, currentproj):
		GeneratedGUI.OpenProjectDialog.__init__( self, parent )
		self._fact = fact
		self._currentproj = currentproj
		self._listed_projects = []

	@property
	def chosenproject(self):
		return self._chosenproject
		
	# Handlers for OpenProjectDialog events.
	def m_checkBox2OnCheckBox( self, event ):
		# TODO: Implement m_checkBox2OnCheckBox
		pass

	def dook(self):
		selidx = self.m_projectsLCTRL.GetFirstSelected()
		if selidx == wx.NOT_FOUND:
			wx.MessageBox("Please select a project", caption="Message", parent=self)
			return

		self._chosenproject = self._listed_projects[selidx]
		self.EndModal(wx.ID_OK)
	
	def m_sdbSizer2OnOKButtonClick( self, event ):
		self.dook()
	

	def OpenProjectDialogOnShow(self, event):
		if event.Show==False:
			return

		self.m_sdbSizer2OK.Enable(False) #gets enabled when something is selected
		self._get_n_show_projects()



	def _get_n_show_projects(self, archived=False):
		proj_q = sqp.SQQuery(self._fact, Project).where(Project.IsArchived==archived)

		self._listed_projects.clear()
		self.m_projectsLCTRL.ClearAll()
		self.m_projectsLCTRL.InsertColumn(0, 'name', width = 100) 
		self.m_projectsLCTRL.InsertColumn(1, 'state', 100) 
		self.m_projectsLCTRL.InsertColumn(2, 'archived', wx.LIST_FORMAT_RIGHT, 100)
		
		for proj in proj_q:
			self._listed_projects.append(proj)
			idx = self.m_projectsLCTRL.InsertItem(self.m_projectsLCTRL.GetItemCount(), proj.name)
			if proj.status is not None:
				self.m_projectsLCTRL.SetItem(idx, 1, proj.status.value)
			self.m_projectsLCTRL.SetItem(idx, 2, str(proj.isarchived))

	def m_projectsLCTRLOnLeftDClick(self, event):
		self.dook()


	def m_projectsLCTRLOnListItemDeselected(self, event):
		self.m_sdbSizer2OK.Enable(False)

	def m_projectsLCTRLOnListItemSelected(self, event):
		self.m_sdbSizer2OK.Enable()

		

