"""Subclass of AddResponseDialog, which is generated by wxFormBuilder."""

import wx
import GeneratedGUI
from PersistClasses import ResponseDefinition
import sqlitepersist as sqp

# Implementing AddResponseDialog
class PexDbViewerAddResponseDialog( GeneratedGUI.AddResponseDialog ):
	def __init__( self, parent, fact : sqp.SQFactory, alreadyconnected : list ):
		GeneratedGUI.AddResponseDialog.__init__( self, parent )
		self._alrconn = alreadyconnected
		self._fact = fact
		self._selectedresponse = None
		self._responselist = []

	@property
	def selectedresponse(self):
		return self._selectedresponse


	# Handlers for AddResponseDialog events.
	def AddResponseDialogOnShow( self, event ):
		if event.Show is False:
			return

		factdef_q = sqp.SQQuery(self._fact, ResponseDefinition).where(ResponseDefinition.IsActive==True and sqp.NotIsIn(ResponseDefinition.Id, self._alrconn))
		
		self.m_responsesLCTR.ClearAll()
		self.m_responsesLCTR.InsertColumn(0, "Name", width=160)
		self.m_responsesLCTR.InsertColumn(1, "Unit")
		self._responselist = list(factdef_q)
		ct = 0
		for resp in self._responselist:
			idx = self.m_responsesLCTR.InsertItem(self.m_responsesLCTR.GetColumnCount(), resp.name)
			self.m_responsesLCTR.SetItemData(idx, ct)
			if not resp.unit is None:
				self.m_responsesLCTR.SetItem(idx, 1, resp.unit.abbreviation)

			ct += 1

	def dook(self):
		selidx = self.m_responsesLCTR.GetFirstSelected()
		if selidx == wx.NOT_FOUND:
			wx.MessageBox("Please select a response from the list")
			return
		
		idx = self.m_responsesLCTR.GetItemData(selidx)
		self._selectedresponse = self._responselist[idx]
		self.EndModal(wx.ID_OK)

	def m_factorsLCTROnLeftDClick( self, event ):
		self.dook()


	def m_factorsLCTROnListItemDeselected( self, event ):
		self.m_sdbSizer3OK.Enable(False)


	def m_factorsLCTROnListItemSelected( self, event ):
		self.m_sdbSizer3OK.Enable()


	def m_sdbSizer3OnOKButtonClick( self, event ):
		self.dook()


