"""Subclass of AddSubElementDialog, which is generated by wxFormBuilder."""

import wx
import logging
import GeneratedGUI
import sqlitepersist as sqp
from sqlitepersist.SQLitePersistBasicClasses import PBase
from PersistClasses import *

# Implementing AddSubElementDialog
class PexDbViewerAddSubElementDialog( GeneratedGUI.AddSubElementDialog ):

	def __init__( self, parent, fact : sqp.SQFactory, presentthese : sqp.SQQuery, objname):
		GeneratedGUI.AddSubElementDialog.__init__( self, parent)
		self._fact = fact
		self._pres_q = presentthese
		self._selected = None
		self._objectlist = []
		self._oname = objname
		self._logger = logging.getLogger("mainprog")
		self._do_init_dialog()

	@property
	def selected(self):
		return self._selected

	def _do_init_dialog(self):
		self._logger.debug("_do_init_dialog() startet in %s for objname <%s>", 
			self.__class__.__name__,
			self._oname)

		tit = self.GetTitle()
		self.SetTitle(tit.format(self._oname))
		lheading = self.m_listHeadingSTXT.GetLabel()
		self.m_listHeadingSTXT.SetLabel(lheading.format(self._oname))
		self.m_objectsLLCTR.ClearAll()
		self.m_objectsLLCTR.InsertColumn(0, "Name")
		self.m_objectsLLCTR.InsertColumn(1, "Unit")

	def AddSubElementDialogOnShow(self, event):
		self._logger.debug("DialogOnShow() for instance of %s, event.Show <%s>", 
			self.__class__.__name__,
			event.Show)

		if event.Show is False:
			return

		self._logger.debug("Preparing list for %d objects", len(self._objectlist))

		self._objectlist = list(self._pres_q)
		ct = 0
		self.m_objectsLLCTR.DeleteAllItems()
		for obj in self._objectlist:
			self._logger.debug("Adding element <%s>", obj.name)
			idx = self.m_objectsLLCTR.InsertItem(self.m_objectsLLCTR.GetColumnCount(), obj.name)
			self.m_objectsLLCTR.SetItemData(idx, ct)
			self.m_objectsLLCTR.SetItem(idx, 1, self._get_unit_str(obj.unit))
			ct += 1

		self.Fit()


	def _get_unit_str(self, uni : Unit) -> str:
		if uni is None:
			return "-unitless-"
		elif type(uni) is Unit:
			return uni.abbreviation
		else:
			raise Exception("argument type must be none or of type Unit")

	def dook(self):
		selidx = self.m_objectsLLCTR.GetFirstSelected()
		if selidx == wx.NOT_FOUND:
			wx.MessageBox("Please select a {} in the list".format(self._oname))
			return
		
		idx = self.m_objectsLLCTR.GetItemData(selidx)
		self._selected = self._objectlist[idx]
		self.EndModal(wx.ID_OK)

	def m_sdbSizer3OnOKButtonClick(self, event):
		self.dook()

	def m_objectsLLCTROnListItemSelected(self, event):
		self.m_sdbSizer3OK.Enable()

	def m_objectsLLCTROnListItemDeselected(self, event):
		self.m_sdbSizer3OK.Enable(False)

	def m_objectsLLCTROnLeftDClick(self, event):
		self.dook()