"""Subclass of EditResponsePreparation, which is generated by wxFormBuilder."""

import locale
import wx
import logging
import GeneratedGUI
from PersistClasses import ProjectResponsePreparation
from Validators import FloatValidator

# Implementing EditResponsePreparation
class PexDbViewerEditResponsePreparation( GeneratedGUI.EditResponsePreparation ):
	def __init__( self, parent, prep : ProjectResponsePreparation):
		GeneratedGUI.EditResponsePreparation.__init__( self, parent )
		self._respprep = prep
		self._do_init_dialog()
		self._logger = logging.getLogger("mainprog")

	@property
	def respprep(self):
		return self._respprep

	def _do_init_dialog(self):
		self.m_combiWeightTCTRL.SetValidator(FloatValidator((0.0, 1.0)))
		valstr = ""
		if self._respprep.combinationweight is not None:
			valstr = locale.str(self._respprep.combinationweight)

		self.m_combiWeightTCTRL.SetValue(valstr)

	def m_sdbSizer8OnOKButtonClick(self, event):
		if self.Validate():
			valstr = self.m_combiWeightTCTRL.GetValue()
			self._respprep.combinationweight = locale.atof(valstr)

			self.EndModal(wx.ID_OK)

