"""Subclass of AddSubElementDialog, which is generated by wxFormBuilder."""

import wx
import GeneratedGUI
import sqlitepersist as sqp
from sqlitepersist.SQLitePersistBasicClasses import PBase

# Implementing AddSubElementDialog
class PexDbViewerAddSubElementDialog( GeneratedGUI.AddSubElementDialog ):

	def __init__( self, parent, fact : sqp.SQFactory, selcls, objname, alreadyconnected : list):
		GeneratedGUI.AddSubElementDialog.__init__( self, parent)
		self._alrconn = alreadyconnected
		self._fact = fact
		self._selected = None
		self._objectlist = []
		self._sc = selcls
		self._oname = objname

	@property
	def selected(self):
		return self._selected

	def AddSubElementDialogOnInitDialog(self, event):
		tit = self.GetTitle()
		self.SetTitle(tit.format(self._oname))
		lheading = self.m_listHeadingSTXT.GetLabel()
		self.m_listHeadingSTXT.SetLabel(lheading.format(self._oname))

	def AddSubElementDialogOnShow(self, event):
		if event.Show is False:
			return

		objectdef_q = sqp.SQQuery(self._fact, self._sc).where(self._sc.IsActive==True and sqp.NotIsIn(self._sc.Id, self._alrconn))
		
		self.m_objectsLLCTR
		self.m_objectsLLCTR.ClearAll()
		self.m_objectsLLCTR.InsertColumn(0, "Name")
		self.m_objectsLLCTR.InsertColumn(1, "Unit")
		self._objectlist = list(objectdef_q)
		ct = 0
		for obj in self._objectlist:
			idx = self.m_objectsLLCTR.InsertItem(self.m_objectsLLCTR.GetColumnCount(), obj.name)
			self.m_objectsLLCTR.SetItemData(idx, ct)
			self.m_objectsLLCTR.SetItem(idx, 1, obj.unit.abbreviation)
			ct += 1

	def dook(self):
		selidx = self.m_objectsLLCTR.GetFirstSelected()
		if selidx == wx.NOT_FOUND:
			wx.MessageBox("Please select a {} in the list".format(self._oname))
			return
		
		idx = self.m_objectsLLCTR.GetItemData(selidx)
		self._selected = self._objectlist[idx]
		self.EndModal(wx.ID_OK)

	def m_sdbSizer3OnOKButtonClick(self, event):
		self.dook()

	def m_objectsLLCTROnListItemDeselected(self, event):
		self.m_sdbSizer3OK.Enable()


	def m_objectsLLCTROnListItemDeselected(self, event):
		self.m_sdbSizer3OK.Enable(False)

	def m_objectsLLCTROnLeftDClick(self, event):
		self.dook()