"""Subclass of AboutDialog, which is generated by wxFormBuilder."""
from importlib.metadata import metadata, version
import wx
import GeneratedGUI

# Implementing AboutDialog
class PexDbViewerAboutDialog( GeneratedGUI.AboutDialog ):
	def __init__( self, parent ):
		GeneratedGUI.AboutDialog.__init__( self, parent )
		self._progversion = parent._version

	# Handlers for AboutDialog events.
	def AboutDialogOnInitDialog( self, event ):
		htxt = "<html><body>"
		htxt += "</body></html>"
		htxt += "<h1>About PexDB V{}</h1><p>".format(self._progversion)
		htxt += "PexDB is a database and calculation tool for planning and evaluation of experiments with the "
		htxt += "aim of optimising the quality of FDM 3D prints. Ideas derived from DOE (design of experiments) "
		htxt += "are applied to achieve this."
		htxt += "</p><p>"

		htxt += "The following python modules and program libraries are used for PexDB:"
		htxt += "</p><p>"

		htxt += "<table>"
		htxt += "<tr>"
		htxt += "<td><b>{}</b></td>".format("Name") 
		htxt += "<td><b>{}</b></td>".format("Version") 
		htxt += "<td><b>{}</b></td>".format("Summary") 
		htxt += "</tr>"
		htxt += self._modinfo("matplotlib")
		htxt += self._modinfo("pandas")
		htxt += self._modinfo("pyDOE2")
		htxt += self._modinfo("scikit-learn")
		htxt += self._modinfo("wxPython")
		htxt += "</table></p>"
		self.m_aboutTxtHTML.SetPage(htxt)

	def m_okBUTOnButtonClick(self, event):
		self.Close()

	def _modinfo(self, modname : str):
		try:
			md = metadata(modname)
			name = md["Name"]
			vers = md["Version"]
			summ = md["Summary"]
		except:
			name = modname
			vers = "./."
			summ = "./."
		
		return "<tr><td>{}</td><td>{}</td><td>{}</td></tr>".format(name, vers, summ)


