"""Subclass of EditPreparation, which is generated by wxFormBuilder."""

import wx
import GeneratedGUI
import sqlitepersist as sqp

from PersistClasses import ProjectFactorPreparation

# Implementing EditPreparation
class PexDbViewerEditPreparation( GeneratedGUI.EditPreparation ):
	def __init__( self, parent, prep : ProjectFactorPreparation ):
		GeneratedGUI.EditPreparation.__init__( self, parent )

		self._prep = prep
		self._editedprep = None

	@property
	def editedprep(self):
		return self._editedprep

	def EditPreparationOnShow(self, event):
		self.m_maxValTBX.SetValue(str(self._prep.maxvalue))
		self.m_minValTBX.SetValue(str(self._prep.minvalue))
		self.m_numLvlsTBX.SetValue(str(self._prep.levelnum))


	# Handlers for EditPreparation events.
	def OnOKButtonClick( self, event ):
		ediprep = self._prep
		ediprep.minvalue = float(self.m_minValTBX.GetValue())
		ediprep.maxvalue = float(self.m_maxValTBX.GetValue())
		ediprep.levelnum = int(self.m_numLvlsTBX.GetValue())

		self._editedprep = ediprep
		self.EndModal(wx.ID_OK)
