"""Subclass of LinRegrDialog.py, which is generated by wxFormBuilder."""
from pandas.core.frame import DataFrame
import wx
import GeneratedGUI
from PersistClasses import *
from MultiReg import *

# Implementing LinRegrDialog.py
class PexDbViewerLinRegrDialog( GeneratedGUI.LinRegrDialog ):
	def __init__( self, parent, fact : sqp.SQFactory, proj : Project ):
		GeneratedGUI.LinRegrDialog.__init__(self, parent)
		self._f = fact
		self._p = proj

	def LinRegrDialogOnInitDialog( self, event ):
		self._solver = MultiReg(self._f, self._p)
		self._solver.read_data()
		


	def LinRegrDialogOnShow( self, event ):
		if event.Show is False:
			return

		df = self._solver.dataframe
		grdf = df.groupby(["repnum"])
		meanl = []
		
		for rprep in sqp.SQQuery(self._f, ProjectResponsePreparation).where(ProjectResponsePreparation.ProjectId==self._p._id):
			meanl.append(rprep.responsedefinition.abbreviation)	
		
		mi = grdf.mean(meanl)
		std= grdf.std()
		
		col = self.m_inputDataDLCTRL.InsertColumn(self.m_inputDataDLCTRL.GetColumnCount(), "#")
		for abbr, name in self._solver.factdict.items():
			col = self.m_inputDataDLCTRL.InsertColumn(col, name)

		for abbr, name in self._solver.respdict.items():
			self.m_inputDataDLCTRL.InsertColumn(col, name)
