"""Subclass of EditResultDefinitions, which is generated by wxFormBuilder."""

import wx
import sqlitepersist as sqp
import PropGridGUIMappers as pgum
from PersistClasses import *
import GeneratedGUI

# Implementing EditResultDefinitions
class PexDbViewerEditResultDefinitions(GeneratedGUI.EditResultDefinitions):
	def __init__(self, parent, sqpfactory : sqp.SQFactory):
		if sqpfactory is None:
			raise Exception("please supply a sqlite persist factory on init of this gui class")

		GeneratedGUI.EditResultDefinitions.__init__( self, parent )

		self._fact = sqpfactory
		self._factor_defs = []
		self._currentfdef = None
		self._currentactive = True

	# Handlers for EditResultDefinitions events.
	def EditFactorDefinitionsOnShow(self, event):
		# WxGuiMapperResultDefintion
		#the dialog is shown or deshown

		if event.Show is False: #the dialog was closed
			return

		self._factgui = pgum.WxGuiMapperResultDefintion(self._fact, self.m_resultDtaPG)
		self.get_dbdta2gui(True)


	def get_dbdta2gui(self, active = True):
		self._factgui.emtyallitems(self.m_resultDtaPG)
		self.m_resultDtaPG.Enable(False) #deisable the prop grid, will be enabled in case a factor gets selected by the user

		self.m_factorDefsLC.DeleteAllItems()
		self.m_factorDefsLC.DeleteAllColumns()

		fact_q = sqp.SQQuery(self._fact, ResultDefinition).where(ResultDefinition.IsActive==active).order_by(ResultDefinition.Name)

		self.m_factorDefsLC.InsertColumn(0, "abbreviation")
		self.m_factorDefsLC.InsertColumn(1, "name")
		self.m_factorDefsLC.InsertColumn(2, "active")
		ct = 0
		self._factor_defs.clear()
		for fact in fact_q:
			self._factor_defs.append(fact)
			lidx = self.m_factorDefsLC.InsertItem(self.m_factorDefsLC.GetItemCount(), fact.abbreviation)
			self.m_factorDefsLC.SetItemData(lidx, ct)
			self.m_factorDefsLC.SetItem(lidx, 1, fact.name)
			self.m_factorDefsLC.SetItem(lidx, 2, str(fact.isactive))
			ct += 1

		self._currentactive = active #store this to enable toggling
		#if we got any factors - select the fist one
		if ct > 0:
			self.m_factorDefsLC.Select(0)

	def _get_as_item(self, fact, id) -> wx.ListItem:
		li = wx.ListItem()
		li.SetData(id) #store initial sequence number as data to be able to find the full data in local list with this id
		li.SetText(fact.name)
		li.SetId(id)
		return li

	def m_factorDefsLCOnListItemSelected( self, event ):
		selidx = self.m_factorDefsLC.GetFirstSelected()
		if selidx < 0:
			return

		self.m_resultDtaPG.Enable() #enable the property grid because a factor was selected to be edited
		myidx = self.m_factorDefsLC.GetItemData(selidx)
		selfactdef = self._factor_defs[myidx]
		self._currentfdef = selfactdef
		valdict = {}
		fetchthese = ["name", "abbreviation", "unit", "isactive"]
		for attnam in fetchthese:
			valdict[attnam] = selfactdef.__getattribute__(attnam)

		self._factgui.object2gui(valdict, self.m_resultDtaPG)

	def m_factorDtaPGOnPropertyGridChanged( self, event ):
		vald = self._factgui.gui2object(self.m_resultDtaPG)
		fetchthese = ["name", "abbreviation", "unit", "unitid", "isactive"]
		for name in fetchthese:
			self._currentfdef.__setattr__(name, vald[name])

		self._fact.flush(self._currentfdef)

	def m_closeBUOnButtonClick( self, event ):
		self.Close()


	def m_newBUOnButtonClick( self, event ):
		newFact = ResultDefinition(name="new result definition", abbreviation="_NEWRES")
		self._fact.flush(newFact)
		self.get_dbdta2gui(active=True)

	def m_show_inactiveBUOnButtonClick( self, event ):
		#toggle active/inactive 
		self.get_dbdta2gui(active = not self._currentactive)



